### ISSUE TITLE
Svg is not loading in production

### ISSUE THREAD

**Issue by firedev** [mrfoto/swipebox#4]
Hi, 

SVG is not loading in production somehow. Development is fine. Here is what I see in Network log:

```
/assets/swipebox-icons-54ac5cc2e33d7110ec5fee2d050f46e8.png – 200
/assets/swipebox-icons-54ac5cc2e33d7110ec5fee2d050f46e8.svg – 404
```
When I compile assets manually the hash is different:

```
I, [2015-03-06T10:02:43.800675 #39826]  INFO -- : Writing 
/[...]/assets/swipebox-icons-54ac5cc2e33d7110ec5fee2d050f46e8.png
I, [2015-03-06T10:02:43.801717 #39826]  INFO -- : Writing 
/[...]/assetsswipebox-icons-2a000235eb3b307f2aa9f596c043facd.svg
```

But it tries to load the wrong one:

```
<a id="swipebox-close" style="background-image: 
url([...]/assets/swipebox-icons-54ac5cc2e33d7110ec5fee2d050f46e8.svg);"></a>
```

Please advise. Thanks.

**Comment by firedev** [comment]
I see why, I had to patch swipebox and this is what's causing it:

```
          bg = bg.replace( 'png', 'svg' );
```

**Comment by mrfoto** [comment]
You're clearly not using my gem :confused: 
I take care with this with https://github.com/mrfoto/swipebox/blob/master/vendor/assets/javascripts/swipebox.js#L167-L169

**Comment by firedev** [comment]
I do use your gem, but had to patch the original `swipebox.js` to get rid of duplicates https://github.com/brutaldesign/swipebox/issues/210

Thought your css would override the original styling. But no worries, I just disabled svg for now.

**Comment by mrfoto** [comment]
Why? My gem includes the patched js :confused:

**Comment by firedev** [comment]
I have links to images repeated a few times on the page. So I had to prevent duplicates in gallery.
